[package]
name = "pcf8563-async"
version = "0.3.0"
authors = ["Michal Lasak <nebelgrau77@gmail.com>"]
edition = "2021"
description = "Platform-agnostic Rust driver for the NXP PCF8563 real-time clock."
documentation = "https://docs.rs/pcf8563"
readme = "README.md"
homepage = "https://github.com/nebelgrau77/pcf8563-rs"
repository = "https://github.com/nebelgrau77/pcf8563-rs"
license = "MIT OR Apache-2.0"
keywords = ["pcf8563", "rtc", "clock", "driver", "embedded-hal-driver", "async"]
categories = ["embedded", "hardware-support", "no-std", "async"]

include = [
    "**/*.rs",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/README.md",
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
    ]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
defmt = "1.0.1"
embedded-hal-async = "1.0.0"

[dev-dependencies]
embedded-hal-mock = "0.2"

[profile.release]
lto = true
